### ISSUE TITLE
skgnet训练准确率在cornell上仅有60%

### ISSUE THREAD

**Issue by wngkj** [BIT-robot-group/SE-ResUNet#1]
你好，使用models里的sknet网络进行训练，按照skgnet原论文的训练参数设置，准确率仅有60%左右，是网络代码还需要什么修改或者设置吗？

**Comment by CaptainDaoshi** [comment]
> 你好，使用models里的sknet网络进行训练，按照skgnet原论文的训练参数设置，准确率仅有60%左右，是网络代码还需要什么修改或者设置吗？

你好，请问有结果了嘛，我训练的准确率也不高

**Comment by qingchenkanlu** [comment]
您好，我目前不确定你们那边出现了什么情况，我当时训练测试的时候是没有问题的，因为过的时间太长了，我也忘了我当初的设定状况。我已经上传了网络的预训练权重，我在本地测试的时候结果是没有问题的
INFO:root:CUDA detected. Running with GPU acceleration.
INFO:root:Loading Cornell Dataset...
INFO:root:Validation size: 89
INFO:root:Done
INFO:root:
Evaluating model logs/cornell/epoch_26_iou_0.93
INFO:root:Average evaluation time per image: 131.96832142519148ms
INFO:root:IOU Results: 88/89 = 0.988764


我把网络结构附在上面，你们可以按照样子修改，主要是目前比较繁忙，没有很多时间来进行详细的解答，抱歉，有问题可以继续留言
        Layer (type)               Output Shape         Param 
            Conv2d-1         [-1, 64, 224, 224]           2,368
       BatchNorm2d-2         [-1, 64, 224, 224]             128
            Conv2d-3         [-1, 64, 112, 112]          65,600
       BatchNorm2d-4         [-1, 64, 112, 112]             128
            Conv2d-5         [-1, 64, 112, 112]           4,160
       BatchNorm2d-6         [-1, 64, 112, 112]             128
            Conv2d-7           [-1, 64, 56, 56]           4,672
       BatchNorm2d-8           [-1, 64, 56, 56]             128
              ReLU-9           [-1, 64, 56, 56]               0
           Conv2d-10           [-1, 64, 56, 56]          12,864
      BatchNorm2d-11           [-1, 64, 56, 56]             128
             ReLU-12           [-1, 64, 56, 56]               0
           Linear-13                   [-1, 32]           2,080
           Linear-14                   [-1, 64]           2,112
           Linear-15                   [-1, 64]           2,112
          Softmax-16                [-1, 2, 64]               0
           SKConv-17           [-1, 64, 56, 56]               0
      BatchNorm2d-18           [-1, 64, 56, 56]             128
           Conv2d-19          [-1, 128, 56, 56]           8,320
      BatchNorm2d-20          [-1, 128, 56, 56]             256
           Conv2d-21          [-1, 128, 56, 56]           8,320
      BatchNorm2d-22          [-1, 128, 56, 56]             256
           SKUnit-23          [-1, 128, 56, 56]               0
             ReLU-24          [-1, 128, 56, 56]               0
           Conv2d-25           [-1, 64, 56, 56]           8,256
      BatchNorm2d-26           [-1, 64, 56, 56]             128
           Conv2d-27           [-1, 64, 56, 56]           4,672
      BatchNorm2d-28           [-1, 64, 56, 56]             128
             ReLU-29           [-1, 64, 56, 56]               0
           Conv2d-30           [-1, 64, 56, 56]          12,864
      BatchNorm2d-31           [-1, 64, 56, 56]             128
             ReLU-32           [-1, 64, 56, 56]               0
           Linear-33                   [-1, 32]           2,080
           Linear-34                   [-1, 64]           2,112
           Linear-35                   [-1, 64]           2,112
          Softmax-36                [-1, 2, 64]               0
           SKConv-37           [-1, 64, 56, 56]               0
      BatchNorm2d-38           [-1, 64, 56, 56]             128
           Conv2d-39          [-1, 128, 56, 56]           8,320
      BatchNorm2d-40          [-1, 128, 56, 56]             256
           SKUnit-41          [-1, 128, 56, 56]               0
             ReLU-42          [-1, 128, 56, 56]               0
           Conv2d-43          [-1, 128, 56, 56]          16,512
      BatchNorm2d-44          [-1, 128, 56, 56]             256
           Conv2d-45          [-1, 128, 28, 28]          18,560
      BatchNorm2d-46          [-1, 128, 28, 28]             256
             ReLU-47          [-1, 128, 28, 28]               0
           Conv2d-48          [-1, 128, 28, 28]          51,328
      BatchNorm2d-49          [-1, 128, 28, 28]             256
             ReLU-50          [-1, 128, 28, 28]               0
           Linear-51                   [-1, 64]           8,256
           Linear-52                  [-1, 128]           8,320
           Linear-53                  [-1, 128]           8,320
          Softmax-54               [-1, 2, 128]               0
           SKConv-55          [-1, 128, 28, 28]               0
      BatchNorm2d-56          [-1, 128, 28, 28]             256
           Conv2d-57          [-1, 256, 28, 28]          33,024
      BatchNorm2d-58          [-1, 256, 28, 28]             512
           Conv2d-59          [-1, 256, 28, 28]          33,024
      BatchNorm2d-60          [-1, 256, 28, 28]             512
           SKUnit-61          [-1, 256, 28, 28]               0
             ReLU-62          [-1, 256, 28, 28]               0
           Conv2d-63          [-1, 128, 28, 28]          32,896
      BatchNorm2d-64          [-1, 128, 28, 28]             256
           Conv2d-65          [-1, 128, 28, 28]          18,560
      BatchNorm2d-66          [-1, 128, 28, 28]             256
             ReLU-67          [-1, 128, 28, 28]               0
           Conv2d-68          [-1, 128, 28, 28]          51,328
      BatchNorm2d-69          [-1, 128, 28, 28]             256
             ReLU-70          [-1, 128, 28, 28]               0
           Linear-71                   [-1, 64]           8,256
           Linear-72                  [-1, 128]           8,320
           Linear-73                  [-1, 128]           8,320
          Softmax-74               [-1, 2, 128]               0
           SKConv-75          [-1, 128, 28, 28]               0
      BatchNorm2d-76          [-1, 128, 28, 28]             256
           Conv2d-77          [-1, 256, 28, 28]          33,024
      BatchNorm2d-78          [-1, 256, 28, 28]             512
           SKUnit-79          [-1, 256, 28, 28]               0
             ReLU-80          [-1, 256, 28, 28]               0
           Conv2d-81          [-1, 256, 28, 28]          65,792
      BatchNorm2d-82          [-1, 256, 28, 28]             512
           Conv2d-83          [-1, 256, 14, 14]          73,984
      BatchNorm2d-84          [-1, 256, 14, 14]             512
             ReLU-85          [-1, 256, 14, 14]               0
           Conv2d-86          [-1, 256, 14, 14]         205,056
      BatchNorm2d-87          [-1, 256, 14, 14]             512
             ReLU-88          [-1, 256, 14, 14]               0
           Linear-89                  [-1, 128]          32,896
           Linear-90                  [-1, 256]          33,024
           Linear-91                  [-1, 256]          33,024
          Softmax-92               [-1, 2, 256]               0
           SKConv-93          [-1, 256, 14, 14]               0
      BatchNorm2d-94          [-1, 256, 14, 14]             512
           Conv2d-95          [-1, 512, 14, 14]         131,584
      BatchNorm2d-96          [-1, 512, 14, 14]           1,024
           Conv2d-97          [-1, 512, 14, 14]         131,584
      BatchNorm2d-98          [-1, 512, 14, 14]           1,024
           SKUnit-99          [-1, 512, 14, 14]               0
            ReLU-100          [-1, 512, 14, 14]               0
          Conv2d-101          [-1, 256, 14, 14]         131,328
     BatchNorm2d-102          [-1, 256, 14, 14]             512
          Conv2d-103          [-1, 256, 14, 14]          73,984
     BatchNorm2d-104          [-1, 256, 14, 14]             512
            ReLU-105          [-1, 256, 14, 14]               0
          Conv2d-106          [-1, 256, 14, 14]         205,056
     BatchNorm2d-107          [-1, 256, 14, 14]             512
            ReLU-108          [-1, 256, 14, 14]               0
          Linear-109                  [-1, 128]          32,896
          Linear-110                  [-1, 256]          33,024
          Linear-111                  [-1, 256]          33,024
         Softmax-112               [-1, 2, 256]               0
          SKConv-113          [-1, 256, 14, 14]               0
     BatchNorm2d-114          [-1, 256, 14, 14]             512
          Conv2d-115          [-1, 512, 14, 14]         131,584
     BatchNorm2d-116          [-1, 512, 14, 14]           1,024
          SKUnit-117          [-1, 512, 14, 14]               0
            ReLU-118          [-1, 512, 14, 14]               0
 ConvTranspose2d-119          [-1, 256, 29, 29]       2,097,408
     BatchNorm2d-120          [-1, 256, 29, 29]             512
 ConvTranspose2d-121          [-1, 128, 57, 57]         524,416
     BatchNorm2d-122          [-1, 128, 57, 57]             256
 ConvTranspose2d-123         [-1, 64, 113, 113]         131,136
     BatchNorm2d-124         [-1, 64, 113, 113]             128
 ConvTranspose2d-125         [-1, 32, 224, 224]          32,800
     BatchNorm2d-126         [-1, 32, 224, 224]              64
 ConvTranspose2d-127         [-1, 32, 224, 224]          82,976
         Dropout-128         [-1, 32, 224, 224]               0
          Conv2d-129          [-1, 1, 224, 224]              33
         Dropout-130         [-1, 32, 224, 224]               0
          Conv2d-131          [-1, 1, 224, 224]              33
         Dropout-132         [-1, 32, 224, 224]               0
          Conv2d-133          [-1, 1, 224, 224]              33
         Dropout-134         [-1, 32, 224, 224]               0
          Conv2d-135          [-1, 1, 224, 224]              33
Total params: 4,721,540
Trainable params: 4,721,540
Non-trainable params: 0
Input size (MB): 0.77
Forward/backward pass size (MB): 293.93
Params size (MB): 18.01
Estimated Total Size (MB): 312.71

**Comment by wngkj** [comment]
> > 你好，使用models里的sknet网络进行训练，按照skgnet原论文的训练参数设置，准确率仅有60%左右，是网络代码还需要什么修改或者设置吗？
> 
> 你好，请问有结果了嘛，我训练的准确率也不高

很久之前就解决了，现在有些忘了，我记着是网络代码里的某些层被注释掉了，你参照原论文的网络结构把注释的代码恢复就好了

**Comment by wngkj** [comment]
> 您好，我目前不确定你们那边出现了什么情况，我当时训练测试的时候是没有问题的，因为过的时间太长了，我也忘了我当初的设定状况。我已经上传了网络的预训练权重，我在本地测试的时候结果是没有问题的
> INFO:root:CUDA detected. Running with GPU acceleration.
> INFO:root:Loading Cornell Dataset...
> INFO:root:Validation size: 89
> INFO:root:Done
> INFO:root:
> Evaluating model logs/cornell/epoch_26_iou_0.93
> INFO:root:Average evaluation time per image: 131.96832142519148ms
> INFO:root:IOU Results: 88/89 = 0.988764
> 
> 
> 我把网络结构附在上面，你们可以按照样子修改，主要是目前比较繁忙，没有很多时间来进行详细的解答，抱歉，有问题可以继续留言
>         Layer (type)               Output Shape         Param 
>             Conv2d-1         [-1, 64, 224, 224]           2,368
>        BatchNorm2d-2         [-1, 64, 224, 224]             128
>             Conv2d-3         [-1, 64, 112, 112]          65,600
>        BatchNorm2d-4         [-1, 64, 112, 112]             128
>             Conv2d-5         [-1, 64, 112, 112]           4,160
>        BatchNorm2d-6         [-1, 64, 112, 112]             128
>             Conv2d-7           [-1, 64, 56, 56]           4,672
>        BatchNorm2d-8           [-1, 64, 56, 56]             128
>               ReLU-9           [-1, 64, 56, 56]               0
>            Conv2d-10           [-1, 64, 56, 56]          12,864
>       BatchNorm2d-11           [-1, 64, 56, 56]             128
>              ReLU-12           [-1, 64, 56, 56]               0
>            Linear-13                   [-1, 32]           2,080
>            Linear-14                   [-1, 64]           2,112
>            Linear-15                   [-1, 64]           2,112
>           Softmax-16                [-1, 2, 64]               0
>            SKConv-17           [-1, 64, 56, 56]               0
>       BatchNorm2d-18           [-1, 64, 56, 56]             128
>            Conv2d-19          [-1, 128, 56, 56]           8,320
>       BatchNorm2d-20          [-1, 128, 56, 56]             256
>            Conv2d-21          [-1, 128, 56, 56]           8,320
>       BatchNorm2d-22          [-1, 128, 56, 56]             256
>            SKUnit-23          [-1, 128, 56, 56]               0
>              ReLU-24          [-1, 128, 56, 56]               0
>            Conv2d-25           [-1, 64, 56, 56]           8,256
>       BatchNorm2d-26           [-1, 64, 56, 56]             128
>            Conv2d-27           [-1, 64, 56, 56]           4,672
>       BatchNorm2d-28           [-1, 64, 56, 56]             128
>              ReLU-29           [-1, 64, 56, 56]               0
>            Conv2d-30           [-1, 64, 56, 56]          12,864
>       BatchNorm2d-31           [-1, 64, 56, 56]             128
>              ReLU-32           [-1, 64, 56, 56]               0
>            Linear-33                   [-1, 32]           2,080
>            Linear-34                   [-1, 64]           2,112
>            Linear-35                   [-1, 64]           2,112
>           Softmax-36                [-1, 2, 64]               0
>            SKConv-37           [-1, 64, 56, 56]               0
>       BatchNorm2d-38           [-1, 64, 56, 56]             128
>            Conv2d-39          [-1, 128, 56, 56]           8,320
>       BatchNorm2d-40          [-1, 128, 56, 56]             256
>            SKUnit-41          [-1, 128, 56, 56]               0
>              ReLU-42          [-1, 128, 56, 56]               0
>            Conv2d-43          [-1, 128, 56, 56]          16,512
>       BatchNorm2d-44          [-1, 128, 56, 56]             256
>            Conv2d-45          [-1, 128, 28, 28]          18,560
>       BatchNorm2d-46          [-1, 128, 28, 28]             256
>              ReLU-47          [-1, 128, 28, 28]               0
>            Conv2d-48          [-1, 128, 28, 28]          51,328
>       BatchNorm2d-49          [-1, 128, 28, 28]             256
>              ReLU-50          [-1, 128, 28, 28]               0
>            Linear-51                   [-1, 64]           8,256
>            Linear-52                  [-1, 128]           8,320
>            Linear-53                  [-1, 128]           8,320
>           Softmax-54               [-1, 2, 128]               0
>            SKConv-55          [-1, 128, 28, 28]               0
>       BatchNorm2d-56          [-1, 128, 28, 28]             256
>            Conv2d-57          [-1, 256, 28, 28]          33,024
>       BatchNorm2d-58          [-1, 256, 28, 28]             512
>            Conv2d-59          [-1, 256, 28, 28]          33,024
>       BatchNorm2d-60          [-1, 256, 28, 28]             512
>            SKUnit-61          [-1, 256, 28, 28]               0
>              ReLU-62          [-1, 256, 28, 28]               0
>            Conv2d-63          [-1, 128, 28, 28]          32,896
>       BatchNorm2d-64          [-1, 128, 28, 28]             256
>            Conv2d-65          [-1, 128, 28, 28]          18,560
>       BatchNorm2d-66          [-1, 128, 28, 28]             256
>              ReLU-67          [-1, 128, 28, 28]               0
>            Conv2d-68          [-1, 128, 28, 28]          51,328
>       BatchNorm2d-69          [-1, 128, 28, 28]             256
>              ReLU-70          [-1, 128, 28, 28]               0
>            Linear-71                   [-1, 64]           8,256
>            Linear-72                  [-1, 128]           8,320
>            Linear-73                  [-1, 128]           8,320
>           Softmax-74               [-1, 2, 128]               0
>            SKConv-75          [-1, 128, 28, 28]               0
>       BatchNorm2d-76          [-1, 128, 28, 28]             256
>            Conv2d-77          [-1, 256, 28, 28]          33,024
>       BatchNorm2d-78          [-1, 256, 28, 28]             512
>            SKUnit-79          [-1, 256, 28, 28]               0
>              ReLU-80          [-1, 256, 28, 28]               0
>            Conv2d-81          [-1, 256, 28, 28]          65,792
>       BatchNorm2d-82          [-1, 256, 28, 28]             512
>            Conv2d-83          [-1, 256, 14, 14]          73,984
>       BatchNorm2d-84          [-1, 256, 14, 14]             512
>              ReLU-85          [-1, 256, 14, 14]               0
>            Conv2d-86          [-1, 256, 14, 14]         205,056
>       BatchNorm2d-87          [-1, 256, 14, 14]             512
>              ReLU-88          [-1, 256, 14, 14]               0
>            Linear-89                  [-1, 128]          32,896
>            Linear-90                  [-1, 256]          33,024
>            Linear-91                  [-1, 256]          33,024
>           Softmax-92               [-1, 2, 256]               0
>            SKConv-93          [-1, 256, 14, 14]               0
>       BatchNorm2d-94          [-1, 256, 14, 14]             512
>            Conv2d-95          [-1, 512, 14, 14]         131,584
>       BatchNorm2d-96          [-1, 512, 14, 14]           1,024
>            Conv2d-97          [-1, 512, 14, 14]         131,584
>       BatchNorm2d-98          [-1, 512, 14, 14]           1,024
>            SKUnit-99          [-1, 512, 14, 14]               0
>             ReLU-100          [-1, 512, 14, 14]               0
>           Conv2d-101          [-1, 256, 14, 14]         131,328
>      BatchNorm2d-102          [-1, 256, 14, 14]             512
>           Conv2d-103          [-1, 256, 14, 14]          73,984
>      BatchNorm2d-104          [-1, 256, 14, 14]             512
>             ReLU-105          [-1, 256, 14, 14]               0
>           Conv2d-106          [-1, 256, 14, 14]         205,056
>      BatchNorm2d-107          [-1, 256, 14, 14]             512
>             ReLU-108          [-1, 256, 14, 14]               0
>           Linear-109                  [-1, 128]          32,896
>           Linear-110                  [-1, 256]          33,024
>           Linear-111                  [-1, 256]          33,024
>          Softmax-112               [-1, 2, 256]               0
>           SKConv-113          [-1, 256, 14, 14]               0
>      BatchNorm2d-114          [-1, 256, 14, 14]             512
>           Conv2d-115          [-1, 512, 14, 14]         131,584
>      BatchNorm2d-116          [-1, 512, 14, 14]           1,024
>           SKUnit-117          [-1, 512, 14, 14]               0
>             ReLU-118          [-1, 512, 14, 14]               0
>  ConvTranspose2d-119          [-1, 256, 29, 29]       2,097,408
>      BatchNorm2d-120          [-1, 256, 29, 29]             512
>  ConvTranspose2d-121          [-1, 128, 57, 57]         524,416
>      BatchNorm2d-122          [-1, 128, 57, 57]             256
>  ConvTranspose2d-123         [-1, 64, 113, 113]         131,136
>      BatchNorm2d-124         [-1, 64, 113, 113]             128
>  ConvTranspose2d-125         [-1, 32, 224, 224]          32,800
>      BatchNorm2d-126         [-1, 32, 224, 224]              64
>  ConvTranspose2d-127         [-1, 32, 224, 224]          82,976
>          Dropout-128         [-1, 32, 224, 224]               0
>           Conv2d-129          [-1, 1, 224, 224]              33
>          Dropout-130         [-1, 32, 224, 224]               0
>           Conv2d-131          [-1, 1, 224, 224]              33
>          Dropout-132         [-1, 32, 224, 224]               0
>           Conv2d-133          [-1, 1, 224, 224]              33
>          Dropout-134         [-1, 32, 224, 224]               0
>           Conv2d-135          [-1, 1, 224, 224]              33
> Total params: 4,721,540
> Trainable params: 4,721,540
> Non-trainable params: 0
> Input size (MB): 0.77
> Forward/backward pass size (MB): 293.93
> Params size (MB): 18.01
> Estimated Total Size (MB): 312.71
> 
> 

好的，感谢，之前已经解决了

**Comment by CaptainDaoshi** [comment]
> > > 你好，使用models里的sknet网络进行训练，按照skgnet原论文的训练参数设置，准确率仅有60%左右，是网络代码还需要什么修改或者设置吗？
> > 
> > 
> > 你好，请问有结果了嘛，我训练的准确率也不高
> 
> 很久之前就解决了，现在有些忘了，我记着是网络代码里的某些层被注释掉了，你参照原论文的网络结构把注释的代码恢复就好了

好的谢谢 我这边应该也没问题了

**Comment by CaptainDaoshi** [comment]
> 您好，我目前不确定你们那边出现了什么情况，我当时训练测试的时候是没有问题的，因为过的时间太长了，我也忘了我当初的设定状况。我已经上传了网络的预训练权重，我在本地测试的时候结果是没有问题的 INFO:root:CUDA detected. Running with GPU acceleration. INFO:root:Loading Cornell Dataset... INFO:root:Validation size: 89 INFO:root:Done INFO:root: Evaluating model logs/cornell/epoch_26_iou_0.93 INFO:root:Average evaluation time per image: 131.96832142519148ms INFO:root:IOU Results: 88/89 = 0.988764
> 
> 我把网络结构附在上面，你们可以按照样子修改，主要是目前比较繁忙，没有很多时间来进行详细的解答，抱歉，有问题可以继续留言 Layer (type) Output Shape Param Conv2d-1 [-1, 64, 224, 224] 2,368 BatchNorm2d-2 [-1, 64, 224, 224] 128 Conv2d-3 [-1, 64, 112, 112] 65,600 BatchNorm2d-4 [-1, 64, 112, 112] 128 Conv2d-5 [-1, 64, 112, 112] 4,160 BatchNorm2d-6 [-1, 64, 112, 112] 128 Conv2d-7 [-1, 64, 56, 56] 4,672 BatchNorm2d-8 [-1, 64, 56, 56] 128 ReLU-9 [-1, 64, 56, 56] 0 Conv2d-10 [-1, 64, 56, 56] 12,864 BatchNorm2d-11 [-1, 64, 56, 56] 128 ReLU-12 [-1, 64, 56, 56] 0 Linear-13 [-1, 32] 2,080 Linear-14 [-1, 64] 2,112 Linear-15 [-1, 64] 2,112 Softmax-16 [-1, 2, 64] 0 SKConv-17 [-1, 64, 56, 56] 0 BatchNorm2d-18 [-1, 64, 56, 56] 128 Conv2d-19 [-1, 128, 56, 56] 8,320 BatchNorm2d-20 [-1, 128, 56, 56] 256 Conv2d-21 [-1, 128, 56, 56] 8,320 BatchNorm2d-22 [-1, 128, 56, 56] 256 SKUnit-23 [-1, 128, 56, 56] 0 ReLU-24 [-1, 128, 56, 56] 0 Conv2d-25 [-1, 64, 56, 56] 8,256 BatchNorm2d-26 [-1, 64, 56, 56] 128 Conv2d-27 [-1, 64, 56, 56] 4,672 BatchNorm2d-28 [-1, 64, 56, 56] 128 ReLU-29 [-1, 64, 56, 56] 0 Conv2d-30 [-1, 64, 56, 56] 12,864 BatchNorm2d-31 [-1, 64, 56, 56] 128 ReLU-32 [-1, 64, 56, 56] 0 Linear-33 [-1, 32] 2,080 Linear-34 [-1, 64] 2,112 Linear-35 [-1, 64] 2,112 Softmax-36 [-1, 2, 64] 0 SKConv-37 [-1, 64, 56, 56] 0 BatchNorm2d-38 [-1, 64, 56, 56] 128 Conv2d-39 [-1, 128, 56, 56] 8,320 BatchNorm2d-40 [-1, 128, 56, 56] 256 SKUnit-41 [-1, 128, 56, 56] 0 ReLU-42 [-1, 128, 56, 56] 0 Conv2d-43 [-1, 128, 56, 56] 16,512 BatchNorm2d-44 [-1, 128, 56, 56] 256 Conv2d-45 [-1, 128, 28, 28] 18,560 BatchNorm2d-46 [-1, 128, 28, 28] 256 ReLU-47 [-1, 128, 28, 28] 0 Conv2d-48 [-1, 128, 28, 28] 51,328 BatchNorm2d-49 [-1, 128, 28, 28] 256 ReLU-50 [-1, 128, 28, 28] 0 Linear-51 [-1, 64] 8,256 Linear-52 [-1, 128] 8,320 Linear-53 [-1, 128] 8,320 Softmax-54 [-1, 2, 128] 0 SKConv-55 [-1, 128, 28, 28] 0 BatchNorm2d-56 [-1, 128, 28, 28] 256 Conv2d-57 [-1, 256, 28, 28] 33,024 BatchNorm2d-58 [-1, 256, 28, 28] 512 Conv2d-59 [-1, 256, 28, 28] 33,024 BatchNorm2d-60 [-1, 256, 28, 28] 512 SKUnit-61 [-1, 256, 28, 28] 0 ReLU-62 [-1, 256, 28, 28] 0 Conv2d-63 [-1, 128, 28, 28] 32,896 BatchNorm2d-64 [-1, 128, 28, 28] 256 Conv2d-65 [-1, 128, 28, 28] 18,560 BatchNorm2d-66 [-1, 128, 28, 28] 256 ReLU-67 [-1, 128, 28, 28] 0 Conv2d-68 [-1, 128, 28, 28] 51,328 BatchNorm2d-69 [-1, 128, 28, 28] 256 ReLU-70 [-1, 128, 28, 28] 0 Linear-71 [-1, 64] 8,256 Linear-72 [-1, 128] 8,320 Linear-73 [-1, 128] 8,320 Softmax-74 [-1, 2, 128] 0 SKConv-75 [-1, 128, 28, 28] 0 BatchNorm2d-76 [-1, 128, 28, 28] 256 Conv2d-77 [-1, 256, 28, 28] 33,024 BatchNorm2d-78 [-1, 256, 28, 28] 512 SKUnit-79 [-1, 256, 28, 28] 0 ReLU-80 [-1, 256, 28, 28] 0 Conv2d-81 [-1, 256, 28, 28] 65,792 BatchNorm2d-82 [-1, 256, 28, 28] 512 Conv2d-83 [-1, 256, 14, 14] 73,984 BatchNorm2d-84 [-1, 256, 14, 14] 512 ReLU-85 [-1, 256, 14, 14] 0 Conv2d-86 [-1, 256, 14, 14] 205,056 BatchNorm2d-87 [-1, 256, 14, 14] 512 ReLU-88 [-1, 256, 14, 14] 0 Linear-89 [-1, 128] 32,896 Linear-90 [-1, 256] 33,024 Linear-91 [-1, 256] 33,024 Softmax-92 [-1, 2, 256] 0 SKConv-93 [-1, 256, 14, 14] 0 BatchNorm2d-94 [-1, 256, 14, 14] 512 Conv2d-95 [-1, 512, 14, 14] 131,584 BatchNorm2d-96 [-1, 512, 14, 14] 1,024 Conv2d-97 [-1, 512, 14, 14] 131,584 BatchNorm2d-98 [-1, 512, 14, 14] 1,024 SKUnit-99 [-1, 512, 14, 14] 0 ReLU-100 [-1, 512, 14, 14] 0 Conv2d-101 [-1, 256, 14, 14] 131,328 BatchNorm2d-102 [-1, 256, 14, 14] 512 Conv2d-103 [-1, 256, 14, 14] 73,984 BatchNorm2d-104 [-1, 256, 14, 14] 512 ReLU-105 [-1, 256, 14, 14] 0 Conv2d-106 [-1, 256, 14, 14] 205,056 BatchNorm2d-107 [-1, 256, 14, 14] 512 ReLU-108 [-1, 256, 14, 14] 0 Linear-109 [-1, 128] 32,896 Linear-110 [-1, 256] 33,024 Linear-111 [-1, 256] 33,024 Softmax-112 [-1, 2, 256] 0 SKConv-113 [-1, 256, 14, 14] 0 BatchNorm2d-114 [-1, 256, 14, 14] 512 Conv2d-115 [-1, 512, 14, 14] 131,584 BatchNorm2d-116 [-1, 512, 14, 14] 1,024 SKUnit-117 [-1, 512, 14, 14] 0 ReLU-118 [-1, 512, 14, 14] 0 ConvTranspose2d-119 [-1, 256, 29, 29] 2,097,408 BatchNorm2d-120 [-1, 256, 29, 29] 512 ConvTranspose2d-121 [-1, 128, 57, 57] 524,416 BatchNorm2d-122 [-1, 128, 57, 57] 256 ConvTranspose2d-123 [-1, 64, 113, 113] 131,136 BatchNorm2d-124 [-1, 64, 113, 113] 128 ConvTranspose2d-125 [-1, 32, 224, 224] 32,800 BatchNorm2d-126 [-1, 32, 224, 224] 64 ConvTranspose2d-127 [-1, 32, 224, 224] 82,976 Dropout-128 [-1, 32, 224, 224] 0 Conv2d-129 [-1, 1, 224, 224] 33 Dropout-130 [-1, 32, 224, 224] 0 Conv2d-131 [-1, 1, 224, 224] 33 Dropout-132 [-1, 32, 224, 224] 0 Conv2d-133 [-1, 1, 224, 224] 33 Dropout-134 [-1, 32, 224, 224] 0 Conv2d-135 [-1, 1, 224, 224] 33 Total params: 4,721,540 Trainable params: 4,721,540 Non-trainable params: 0 Input size (MB): 0.77 Forward/backward pass size (MB): 293.93 Params size (MB): 18.01 Estimated Total Size (MB): 312.71

感谢开源
